root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/wakflo ."
bin = "bin/wakflo"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000 # ms
stop_on_error = true

[log]
time = true

[color]
main = "magenta"
info = "yellow"
error = "red"

[misc]
clean_on_exit = true
