env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - ./scripts/manpages.sh
    - ./scripts/completions.sh

builds:
  -
    binary: wakflo-cli
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    builds:
      - wakflo-cli
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

nfpms:
  - builds:
      - wakflo-cli
    vendor: wakflo
    homepage:  https://github.com/wakflo/wakflo-cli
    maintainer: "Rex Raphael <rex@wakflo.com>"
    description: "A general purpose golang CLI template for Github and Gitlab"
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./manpages/wakflo-cli.1.gz
        dst: /usr/share/man/man1/wakflo-cli.1.gz
        file_info:
          mode: 0644
      - src: ./completions/wakflo-cli.bash
        dst: /usr/share/bash-completion/completions/wakflo-cli
        file_info:
          mode: 0644
      - src: ./completions/wakflo-cli.fish
        dst: /usr/share/fish/vendor_completions.d/wakflo-cli.fish
        file_info:
          mode: 0644
      - src: ./completions/wakflo-cli.zsh
        dst:  /usr/share/zsh/vendor-completions/_wakflo-cli
        file_info:
          mode: 0644

dockers:
- image_templates:
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/FalcoSuessgott/wakflo-cli/master/README.md"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Tom Morelly\",\"email\":\"tommorelly@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=MIT"
  - "--label=org.opencontainers.image.description=A general purpose golang CLI template for Github and Gitlab"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'
  dockerfile:  Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/FalcoSuessgott/wakflo-cli/master/README.md"
  - "--label=io.artifacthub.package.logo-url=https://raw.githubusercontent.com/FalcoSuessgott/wakflo-cli/master/www/static/images/logo.png"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Tom Morelly\",\"email\":\"tommorelly@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=MIT"
  - "--label=org.opencontainers.image.description=A general purpose golang CLI template for Github and Gitlab"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64

docker_manifests:
- name_template: 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}'
  image_templates:
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'
- name_template: 'falcosuessgott/{{.ProjectName}}:latest'
  image_templates:
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/falcosuessgott/{{.ProjectName}}:latest'
  image_templates:
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-amd64'
  - 'ghcr.io/falcosuessgott/{{.ProjectName}}:{{ .Tag }}-arm64'

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999